#!/usr/bin/env python

import sys
import click
import os

from commands import container
from commands import perfectwork


@click.group()
@click.pass_context
@click.version_option("0.1.0", prog_name="CS Control Station")
# @click.pass_context
def cli(ctx):
    """
    \b
    Control Station
    A wrapper around ansible for PerfectWORK Deployment
    """
    pass


cli.add_command(container.container)
cli.add_command(perfectwork.perfectwork)

if __name__ == '__main__':
    cli()