#! /usr/local/bin/ansible-playbook

---
  - hosts: all
    become: yes
    vars:
      ansible_python_interpreter: /usr/bin/python3
    tasks:

    # Create the Docker Container for Application
    - name: Configure {{ PW_container_name }}_CHAINLIT Container
      docker_container:
        name: "{{ PW_container_name }}_CHAINLIT"
        image: "synercatalyst/chainlit:latest"
        state: started
        pull: True
        restart: yes
        restart_policy: always
        privileged: yes
        volumes:
            - "/var/lib/perfectwork/{{ inventory_hostname|upper }}/CONTAINERS/{{ PW_container_name }}/chainlit/app:/app"
        networks:
            - name: '{{ docker_PW_network}}'
        networks_cli_compatible: yes
        ports:
            - "{{ CHAINLIT_port }}:80"
        env:
              OPENAI_API_KEY: '{{OPENAI_API_KEY}}'
              # DATABASE_TYPE: "postgres"
              # DATABASE_PORT: "5432"
              # DATABASE_HOST: "SG01_DB"
              # DATABASE_NAME: "flowise"
              # DATABASE_USER: "{{ PW_db_user }}"
              # DATABASE_PASSWORD: "{{ PW_db_password }}"
              # DATABASE_PATH: /data
              # FLOWISE_USERNAME: '{{ FLOWISE_username }}'
              # FLOWISE_PASSWORD: '{{ FLOWISE_password }}'
        labels:
            traefik.enable={{ traefik_enable }}
            traefik.http.routers.{{ PW_container_name }}_CHAINLIT.rule=Host(`{{ CHAINLIT_server }}`)
            traefik.http.routers.{{ PW_container_name }}_CHAINLIT.tls=true
            traefik.http.routers.{{ PW_container_name }}_CHAINLIT.tls.certresolver=le_resolver
            traefik.http.routers.{{ PW_container_name }}_CHAINLIT.service={{ PW_container_name }}_CHAINLIT  
            traefik.http.services.{{ PW_container_name }}_CHAINLIT.loadbalancer.server.port=80
            traefik.http.middlewares.{{ PW_container_name }}_CHAINLIT.compress=true
          
    - name: Prepare Sample App File - /opt/LLM/chainlit/app/
      copy:
        src: /opt/LLM/chainlit/
        dest: /var/lib/perfectwork/{{ inventory_hostname|upper }}/CONTAINERS/{{ PW_container_name }}/chainlit
        owner: '101'
        group: '102'
        mode: '0766'